package com.frotagestor.services

import com.frotagestor.database.DatabaseFactory
import com.frotagestor.database.models.*
import com.frotagestor.interfaces.TripStatus
import kotlinx.datetime.*
import org.jetbrains.exposed.sql.*
import kotlin.math.*
import io.ktor.client.*
import io.ktor.client.request.*
import io.ktor.client.statement.*
import kotlinx.serialization.json.*
import org.jetbrains.exposed.sql.SqlExpressionBuilder.eq

class AutoTripService(
    private val httpClient: HttpClient = HttpClient()
) {

    companion object {
        private const val MIN_IGNITION_ON_SECONDS = 30
        private const val MIN_TRIP_DURATION_MINUTES = 2.0
        private const val MIN_TRIP_DISTANCE_KM = 0.05
        private const val MIN_MOVED_DISTANCE_KM = 0.02
        private const val PENDING_TRIP_CLEANUP_HOURS = 3
        private const val GEOCODING_API_URL = "https://nominatim.openstreetmap.org/reverse"
    }

    // Cache em memória → PRIMEIRO momento da ignição ligada
    private val ignitionOnCache = mutableMapOf<Int, IgnitionOnEvent>()

    data class IgnitionOnEvent(
        val vehicleId: Int,
        val latitude: Double,
        val longitude: Double,
        val dateTime: LocalDateTime,
        val imei: String
    )

    /**
     * Detecta mudança de estado da ignição e cria/finaliza viagens automaticamente
     */
    suspend fun processIgnitionChange(
        imei: String,
        vehicleId: Int,
        latitude: Double,
        longitude: Double,
        ignition: Boolean,
        dateTime: LocalDateTime,
        speed: Double
    ) {
        if (ignition) {
            handleIgnitionOn(imei, vehicleId, latitude, longitude, dateTime)
        } else {
            handleIgnitionOff(imei, vehicleId, latitude, longitude, dateTime)
        }

        cleanupPendingTrips()
    }
    /**
     * Atualiza viagem em andamento com novos dados GPS
     */
    suspend fun updateActiveTrip(
        imei: String,
        vehicleId: Int,
        latitude: Double,
        longitude: Double,
        dateTime: LocalDateTime,
        speed: Double
    ) {
        // 🔑 Aqui a ignição pendente pode virar viagem
        checkPendingIgnition(vehicleId, dateTime)

        DatabaseFactory.dbQuery {
            val activeTrip = TripsTable
                .selectAll()
                .where {
                    (TripsTable.vehicleId eq vehicleId) and
                            (TripsTable.status eq TripStatus.EM_ANDAMENTO) and
                            (TripsTable.autoGenerated eq true)
                }
                .orderBy(TripsTable.startTime, SortOrder.DESC)
                .limit(1)
                .singleOrNull()

            if (activeTrip != null) {
                val tripId = activeTrip[TripsTable.id]
                val startLat = activeTrip[TripsTable.startLatitude]?.toDouble() ?: latitude
                val startLon = activeTrip[TripsTable.startLongitude]?.toDouble() ?: longitude
                val startTime = activeTrip[TripsTable.startTime]

                val distanceKm = calculateDistance(startLat, startLon, latitude, longitude)
                val durationMinutes = calculateDuration(startTime, dateTime)

                val currentMaxSpeed = activeTrip[TripsTable.maxSpeedKmh]?.toDouble() ?: 0.0
                val newMaxSpeed = maxOf(currentMaxSpeed, speed)
                val avgSpeed = if (durationMinutes > 0) {
                    (distanceKm / durationMinutes) * 60
                } else 0.0

                TripsTable.update({ TripsTable.id eq tripId }) {
                    it[endLatitude] = latitude.toBigDecimal()
                    it[endLongitude] = longitude.toBigDecimal()
                    it[endTime] = dateTime
                    it[TripsTable.distanceKm] = distanceKm.toBigDecimal()
                    it[maxSpeedKmh] = newMaxSpeed.toBigDecimal()
                    it[avgSpeedKmh] = avgSpeed.toBigDecimal()
                }

                println("🔄 Viagem #$tripId atualizada (${distanceKm.format(2)} km)")
            }
        }
    }

    /**
     * Registra ignição ligada, mas SÓ cria viagem após 30 segundos
     */
    private suspend fun handleIgnitionOn(
        imei: String,
        vehicleId: Int,
        latitude: Double,
        longitude: Double,
        dateTime: LocalDateTime
    ) {
        // Já existe ignição pendente → NÃO resetar o timer
        if (ignitionOnCache.containsKey(vehicleId)) {
            return
        }

        // Já existe viagem ativa → ignora
        val existingTrip = DatabaseFactory.dbQuery {
            TripsTable
                .selectAll()
                .where {
                    (TripsTable.vehicleId eq vehicleId) and
                            (TripsTable.status eq TripStatus.EM_ANDAMENTO) and
                            (TripsTable.autoGenerated eq true)
                }
                .singleOrNull()
        }

        if (existingTrip != null) return

        ignitionOnCache[vehicleId] =
            IgnitionOnEvent(vehicleId, latitude, longitude, dateTime, imei)

        println("⏳ Ignição ligada - aguardando ${MIN_IGNITION_ON_SECONDS}s (veículo $vehicleId)")
    }

    /**
     * Verifica se ignição pendente deve ser confirmada (após 30s)
     */
    private suspend fun checkPendingIgnition(vehicleId: Int, currentTime: LocalDateTime) {
        val pending = ignitionOnCache[vehicleId] ?: return

        val elapsedSeconds =
            calculateDuration(pending.dateTime, currentTime) * 60

        if (elapsedSeconds >= MIN_IGNITION_ON_SECONDS) {
            createTripInDatabase(pending)
            ignitionOnCache.remove(vehicleId)
        }
    }

    /**
     * Cria viagem no banco de dados (após validação de tempo)
     */
    private suspend fun createTripInDatabase(event: IgnitionOnEvent) {
        DatabaseFactory.dbQuery {
            val gpsDeviceId = GpsDevicesTable
                .selectAll()
                .where { GpsDevicesTable.imei eq event.imei }
                .singleOrNull()
                ?.get(GpsDevicesTable.id)

            val defaultDriverId = VehiclesTable
                .selectAll()
                .where { VehiclesTable.id eq event.vehicleId }
                .singleOrNull()
                ?.get(VehiclesTable.defaultDriverId)

            val startAddress = getAddressFromCoordinates(event.latitude, event.longitude)

            val tripId = TripsTable.insert {
                it[vehicleId] = event.vehicleId
                it[driverId] = defaultDriverId
                it[TripsTable.gpsDeviceId] = gpsDeviceId
                it[startLatitude] = event.latitude.toBigDecimal()
                it[startLongitude] = event.longitude.toBigDecimal()
                it[startLocation] = startAddress ?: "Localização não disponível"
                it[startTime] = event.dateTime
                it[distanceKm] = 0.toBigDecimal()
                it[status] = TripStatus.EM_ANDAMENTO
                it[autoGenerated] = true
                it[maxSpeedKmh] = 0.toBigDecimal()
                it[avgSpeedKmh] = 0.toBigDecimal()
            }[TripsTable.id]

            println("🚗 Viagem criada #$tripId (veículo ${event.vehicleId})")
        }
    }

    /**
     * Finaliza viagem com validação inteligente
     */
    private suspend fun handleIgnitionOff(
        imei: String,
        vehicleId: Int,
        latitude: Double,
        longitude: Double,
        dateTime: LocalDateTime
    ) {
        // 1. Se havia ignição pendente (ligou/desligou rápido), simplesmente descartar
        if (ignitionOnCache.containsKey(vehicleId)) {
            val pending = ignitionOnCache[vehicleId]!!
            val elapsedSeconds = calculateDuration(pending.dateTime, dateTime) * 60
            ignitionOnCache.remove(vehicleId)
            println("🚫 Ignição descartada - Tempo insuficiente: ${elapsedSeconds.toInt()}s (veículo $vehicleId)")
            return
        }

        // 2. Buscar viagem ativa no banco
        DatabaseFactory.dbQuery {
            val activeTrip = TripsTable
                .selectAll()
                .where {
                    (TripsTable.vehicleId eq vehicleId) and
                            (TripsTable.status eq TripStatus.EM_ANDAMENTO) and
                            (TripsTable.autoGenerated eq true)
                }
                .singleOrNull()

            if (activeTrip == null) {
                println("⚠️ Nenhuma viagem ativa para finalizar (veículo $vehicleId)")
                return@dbQuery
            }

            val tripId = activeTrip[TripsTable.id]
            val startLat = activeTrip[TripsTable.startLatitude]?.toDouble() ?: latitude
            val startLon = activeTrip[TripsTable.startLongitude]?.toDouble() ?: longitude
            val startTime = activeTrip[TripsTable.startTime]

            // Calcular métricas finais
            val totalDistanceKm = calculateDistance(startLat, startLon, latitude, longitude)
            val durationMinutes = calculateDuration(startTime, dateTime)

            // 3. VALIDAÇÃO CRITERIOSA
            val hasMovement = totalDistanceKm >= MIN_MOVED_DISTANCE_KM
            val isMinimalTrip = durationMinutes < MIN_TRIP_DURATION_MINUTES &&
                    totalDistanceKm < MIN_TRIP_DISTANCE_KM

            if (!hasMovement && isMinimalTrip) {
                // Viagem SEM movimentação significativa E muito curta → DESCARTAR
                TripsTable.deleteWhere { TripsTable.id eq tripId }
                println("🗑️ Viagem #$tripId DESCARTADA")
                println("   📏 Distância: ${totalDistanceKm.format(3)} km (< ${MIN_MOVED_DISTANCE_KM} km)")
                println("   ⏱️  Duração: ${durationMinutes.format(1)} min (< ${MIN_TRIP_DURATION_MINUTES} min)")
                return@dbQuery
            }

            // 4. VIAGEM VÁLIDA → Salvar com todos os dados
            val endAddress = getAddressFromCoordinates(latitude, longitude)
            val maxSpeed = activeTrip[TripsTable.maxSpeedKmh]?.toDouble() ?: 0.0
            val avgSpeed = if (durationMinutes > 0) {
                (totalDistanceKm / durationMinutes) * 60
            } else 0.0

            TripsTable.update({ TripsTable.id eq tripId }) {
                it[TripsTable.endLatitude] = latitude.toBigDecimal()
                it[TripsTable.endLongitude] = longitude.toBigDecimal()
                it[TripsTable.endLocation] = endAddress ?: "Localização não disponível"
                it[TripsTable.endTime] = dateTime
                it[TripsTable.distanceKm] = totalDistanceKm.toBigDecimal()
                it[TripsTable.status] = TripStatus.CONCLUIDA
                it[TripsTable.maxSpeedKmh] = maxSpeed.toBigDecimal()
                it[TripsTable.avgSpeedKmh] = avgSpeed.toBigDecimal()
            }

            println("✅ Viagem #$tripId FINALIZADA E SALVA")
            println("   📏 Distância: ${totalDistanceKm.format(2)} km")
            println("   ⏱️  Duração: ${durationMinutes.toInt()} min")
            println("   🚀 Vel. máx: ${maxSpeed.format(1)} km/h | Vel. média: ${avgSpeed.format(1)} km/h")
            println("   📍 Fim: ${endAddress ?: "Não disponível"}")
        }
    }

    /**
     * Limpa viagens órfãs (EM_ANDAMENTO há muito tempo)
     */
    private suspend fun cleanupPendingTrips() {
        DatabaseFactory.dbQuery {
            val cutoffTime = Clock.System.now()
                .minus(PENDING_TRIP_CLEANUP_HOURS, DateTimeUnit.HOUR, TimeZone.currentSystemDefault())
                .toLocalDateTime(TimeZone.currentSystemDefault())

            // Buscar viagens órfãs
            val orphanTrips = TripsTable
                .selectAll()
                .where {
                    (TripsTable.status eq TripStatus.EM_ANDAMENTO) and
                            (TripsTable.startTime less cutoffTime) and
                            (TripsTable.autoGenerated eq true)
                }
                .toList()

            orphanTrips.forEach { trip ->
                val tripId = trip[TripsTable.id]
                val startLat = trip[TripsTable.startLatitude]?.toDouble() ?: 0.0
                val startLon = trip[TripsTable.startLongitude]?.toDouble() ?: 0.0
                val endLat = trip[TripsTable.endLatitude]?.toDouble() ?: startLat
                val endLon = trip[TripsTable.endLongitude]?.toDouble() ?: startLon
                val distance = calculateDistance(startLat, startLon, endLat, endLon)

                if (distance < MIN_MOVED_DISTANCE_KM) {
                    // Sem movimentação → descartar
                    TripsTable.deleteWhere { TripsTable.id eq tripId }
                    println("🧹 Viagem órfã #$tripId descartada (sem movimento)")
                } else {
                    // Com movimentação → finalizar forçadamente
                    TripsTable.update({ TripsTable.id eq tripId }) {
                        it[TripsTable.status] = TripStatus.CONCLUIDA
                        it[TripsTable.distanceKm] = distance.toBigDecimal()
                    }
                    println("🧹 Viagem órfã #$tripId finalizada automaticamente")
                }
            }
        }
    }

    /**
     * Geocoding Reverso: Converte coordenadas em endereço
     */
    private suspend fun getAddressFromCoordinates(latitude: Double, longitude: Double): String? {
        return try {
            val response: HttpResponse = httpClient.get(GEOCODING_API_URL) {
                parameter("lat", latitude)
                parameter("lon", longitude)
                parameter("format", "json")
                parameter("addressdetails", 1)
                header("User-Agent", "FrotaGestor/1.0")
            }

            val jsonResponse = Json.parseToJsonElement(response.bodyAsText()).jsonObject
            val address = jsonResponse["address"]?.jsonObject

            val road = address?.get("road")?.jsonPrimitive?.content
            val suburb = address?.get("suburb")?.jsonPrimitive?.content
            val city = address?.get("city")?.jsonPrimitive?.content
                ?: address?.get("town")?.jsonPrimitive?.content
                ?: address?.get("village")?.jsonPrimitive?.content
            val state = address?.get("state")?.jsonPrimitive?.content

            buildString {
                road?.let { append(it) }
                if (suburb != null && suburb != road) {
                    if (isNotEmpty()) append(", ")
                    append(suburb)
                }
                city?.let {
                    if (isNotEmpty()) append(", ")
                    append(it)
                }
                state?.let {
                    if (isNotEmpty()) append(" - ")
                    append(it)
                }
            }.takeIf { it.isNotEmpty() }

        } catch (e: Exception) {
            println("⚠️ Erro ao buscar endereço: ${e.message}")
            null
        }
    }

    private fun calculateDistance(lat1: Double, lon1: Double, lat2: Double, lon2: Double): Double {
        val earthRadiusKm = 6371.0
        val dLat = Math.toRadians(lat2 - lat1)
        val dLon = Math.toRadians(lon2 - lon1)
        val a = sin(dLat / 2) * sin(dLat / 2) +
                cos(Math.toRadians(lat1)) * cos(Math.toRadians(lat2)) *
                sin(dLon / 2) * sin(dLon / 2)
        val c = 2 * atan2(sqrt(a), sqrt(1 - a))
        return earthRadiusKm * c
    }

    private fun calculateDuration(start: LocalDateTime, end: LocalDateTime): Double {
        val startInstant = start.toInstant(TimeZone.currentSystemDefault())
        val endInstant = end.toInstant(TimeZone.currentSystemDefault())
        val durationMs = (endInstant - startInstant).inWholeMilliseconds
        return durationMs / 60000.0
    }

    private fun Double.format(decimals: Int) = "%.${decimals}f".format(this)
}