package com.frotagestor.services

import com.frotagestor.database.DatabaseFactory
import com.frotagestor.database.models.*
import com.frotagestor.interfaces.TripStatus
import kotlinx.datetime.*
import org.jetbrains.exposed.sql.*
import kotlin.math.*
import io.ktor.client.*
import io.ktor.client.request.*
import io.ktor.client.statement.*
import kotlinx.serialization.json.*
import org.jetbrains.exposed.sql.SqlExpressionBuilder.eq
import kotlinx.coroutines.*

class DailyTripService(
    private val httpClient: HttpClient = HttpClient()
) {

    companion object {
        private const val MIN_VALID_TRIP_DISTANCE_KM = 1.0
        private const val GEOCODING_API_URL = "https://nominatim.openstreetmap.org/reverse"
        private const val END_OF_DAY_HOUR = 23
        private const val END_OF_DAY_MINUTE = 0
    }

    private val farthestPointCache = mutableMapOf<Int, FarthestPoint>()
    private val lastPositionCache = mutableMapOf<Int, LastPosition>()

    data class FarthestPoint(
        val latitude: Double,
        val longitude: Double,
        val distanceFromStart: Double,
        val dateTime: LocalDateTime
    )

    data class LastPosition(
        val latitude: Double,
        val longitude: Double
    )

    fun startDailyCleanup(scope: CoroutineScope) {
        scope.launch {
            while (true) {
                val now = Clock.System.now().toLocalDateTime(TimeZone.currentSystemDefault())
                val nextCleanup = calculateNextCleanupTime(now)
                val delayMs = (nextCleanup.toInstant(TimeZone.currentSystemDefault()) -
                        now.toInstant(TimeZone.currentSystemDefault())).inWholeMilliseconds

                println("🕐 Próxima finalização de viagens diárias: $nextCleanup")

                delay(delayMs)
                finalizeAllDailyTrips()
            }
        }
    }

    private fun calculateNextCleanupTime(now: LocalDateTime): LocalDateTime {
        val today23h = LocalDateTime(
            now.date,
            LocalTime(END_OF_DAY_HOUR, END_OF_DAY_MINUTE)
        )

        return if (now >= today23h) {
            today23h.date.plus(1, DateTimeUnit.DAY)
                .atTime(END_OF_DAY_HOUR, END_OF_DAY_MINUTE)
        } else {
            today23h
        }
    }

    suspend fun processGpsData(
        imei: String,
        vehicleId: Int,
        latitude: Double,
        longitude: Double,
        dateTime: LocalDateTime,
        speed: Double,
        ignition: Boolean
    ) {
        if (!ignition) return

        val today = dateTime.date

        val tripId = DatabaseFactory.dbQuery {
            val existingTrip = TripsTable
                .selectAll()
                .where {
                    (TripsTable.vehicleId eq vehicleId) and
                            (TripsTable.autoGenerated eq true) and
                            (TripsTable.status eq TripStatus.EM_ANDAMENTO)
                }
                .orderBy(TripsTable.startTime, SortOrder.DESC)
                .limit(1)
                .singleOrNull()

            if (existingTrip != null) {
                val tripDate = existingTrip[TripsTable.startTime].date
                if (tripDate == today) {
                    return@dbQuery existingTrip[TripsTable.id]
                } else {
                    finalizeTrip(existingTrip[TripsTable.id])
                }
            }

            createDailyTrip(imei, vehicleId, latitude, longitude, dateTime)
        }

        updateDailyTrip(tripId, latitude, longitude, dateTime, speed)
    }

    private suspend fun createDailyTrip(
        imei: String,
        vehicleId: Int,
        latitude: Double,
        longitude: Double,
        dateTime: LocalDateTime
    ): Int {
        val gpsDeviceId = GpsDevicesTable
            .selectAll()
            .where { GpsDevicesTable.imei eq imei }
            .singleOrNull()
            ?.get(GpsDevicesTable.id)

        val defaultDriverId = VehiclesTable
            .selectAll()
            .where { VehiclesTable.id eq vehicleId }
            .singleOrNull()
            ?.get(VehiclesTable.defaultDriverId)

        val startAddress = getAddressFromCoordinates(latitude, longitude)

        val tripId = TripsTable.insert {
            it[TripsTable.vehicleId] = vehicleId
            it[driverId] = defaultDriverId
            it[TripsTable.gpsDeviceId] = gpsDeviceId
            it[startLatitude] = latitude.toBigDecimal()
            it[startLongitude] = longitude.toBigDecimal()
            it[startLocation] = startAddress ?: "Localização não disponível"
            it[startTime] = dateTime
            it[distanceKm] = 0.toBigDecimal()
            it[status] = TripStatus.EM_ANDAMENTO
            it[autoGenerated] = true
            it[maxSpeedKmh] = 0.toBigDecimal()
        }[TripsTable.id]

        farthestPointCache[tripId] = FarthestPoint(
            latitude = latitude,
            longitude = longitude,
            distanceFromStart = 0.0,
            dateTime = dateTime
        )

        lastPositionCache[tripId] = LastPosition(
            latitude = latitude,
            longitude = longitude
        )

        println("🚗 Viagem diária criada #$tripId (veículo $vehicleId - ${dateTime.date})")
        println("   📍 Início: ${startAddress ?: "Não disponível"}")

        return tripId
    }

    private suspend fun updateDailyTrip(
        tripId: Int,
        latitude: Double,
        longitude: Double,
        dateTime: LocalDateTime,
        speed: Double
    ) {
        DatabaseFactory.dbQuery {
            val trip = TripsTable
                .selectAll()
                .where { TripsTable.id eq tripId }
                .singleOrNull() ?: return@dbQuery

            val startLat = trip[TripsTable.startLatitude]?.toDouble() ?: latitude
            val startLon = trip[TripsTable.startLongitude]?.toDouble() ?: longitude
            val startTime = trip[TripsTable.startTime]
            val currentTotalDistance = trip[TripsTable.distanceKm]?.toDouble() ?: 0.0

            val lastPos = lastPositionCache[tripId]
            val incrementalDistance = if (lastPos != null) {
                calculateDistance(lastPos.latitude, lastPos.longitude, latitude, longitude)
            } else {
                0.0
            }

            val newTotalDistance = currentTotalDistance + incrementalDistance

            lastPositionCache[tripId] = LastPosition(latitude, longitude)

            val distanceFromStart = calculateDistance(startLat, startLon, latitude, longitude)

            val currentFarthest = farthestPointCache[tripId]
            if (currentFarthest == null || distanceFromStart > currentFarthest.distanceFromStart) {
                farthestPointCache[tripId] = FarthestPoint(
                    latitude = latitude,
                    longitude = longitude,
                    distanceFromStart = distanceFromStart,
                    dateTime = dateTime
                )
                println("📍 Novo ponto mais distante: ${distanceFromStart.format(2)} km do início (viagem #$tripId)")
            }

            val durationMinutes = calculateDuration(startTime, dateTime)
            val currentMaxSpeed = trip[TripsTable.maxSpeedKmh]?.toDouble() ?: 0.0
            val newMaxSpeed = maxOf(currentMaxSpeed, speed)

            TripsTable.update({ TripsTable.id eq tripId }) {
                it[endLatitude] = latitude.toBigDecimal()
                it[endLongitude] = longitude.toBigDecimal()
                it[endTime] = dateTime
                it[TripsTable.distanceKm] = newTotalDistance.toBigDecimal()
                it[maxSpeedKmh] = newMaxSpeed.toBigDecimal()
            }

            println("🔄 Viagem #$tripId atualizada (${newTotalDistance.format(2)} km percorridos, ${durationMinutes.toInt()} min)")
        }
    }

    private suspend fun finalizeAllDailyTrips() {
        println("🌙 Finalizando todas as viagens diárias...")

        val finalized = DatabaseFactory.dbQuery {
            val activeTrips = TripsTable
                .selectAll()
                .where {
                    (TripsTable.status eq TripStatus.EM_ANDAMENTO) and
                            (TripsTable.autoGenerated eq true)
                }
                .toList()

            var count = 0
            activeTrips.forEach { trip ->
                val tripId = trip[TripsTable.id]
                finalizeTrip(tripId)
                count++
            }
            count
        }

        println("✅ $finalized viagens finalizadas às 23h")
    }

    private suspend fun finalizeTrip(tripId: Int) {
        DatabaseFactory.dbQuery {
            val trip = TripsTable
                .selectAll()
                .where { TripsTable.id eq tripId }
                .singleOrNull() ?: return@dbQuery

            val startLat = trip[TripsTable.startLatitude]?.toDouble() ?: return@dbQuery
            val startLon = trip[TripsTable.startLongitude]?.toDouble() ?: return@dbQuery
            val startTime = trip[TripsTable.startTime]
            val totalDistanceKm = trip[TripsTable.distanceKm]?.toDouble() ?: 0.0

            val farthestPoint = farthestPointCache[tripId]

            if (farthestPoint == null) {
                println("⚠️ Viagem #$tripId sem cache de ponto distante - usando coordenadas finais")
                return@dbQuery
            }

            val endLat = farthestPoint.latitude
            val endLon = farthestPoint.longitude
            val now = Clock.System.now().toLocalDateTime(TimeZone.currentSystemDefault())
            val durationMinutes = calculateDuration(startTime, now)

            if (totalDistanceKm < MIN_VALID_TRIP_DISTANCE_KM) {
                TripsTable.deleteWhere { TripsTable.id eq tripId }
                farthestPointCache.remove(tripId)
                lastPositionCache.remove(tripId)
                println("🗑️ Viagem #$tripId DELETADA - sem movimentação significativa")
                println("   📏 Distância percorrida: ${totalDistanceKm.format(3)} km (< ${MIN_VALID_TRIP_DISTANCE_KM} km)")
                return@dbQuery
            }

            val endAddress = getAddressFromCoordinates(endLat, endLon)
            val maxSpeed = trip[TripsTable.maxSpeedKmh]?.toDouble() ?: 0.0
            val avgSpeed = if (durationMinutes > 0) {
                (totalDistanceKm / durationMinutes) * 60
            } else 0.0

            TripsTable.update({ TripsTable.id eq tripId }) {
                it[TripsTable.endLatitude] = endLat.toBigDecimal()
                it[TripsTable.endLongitude] = endLon.toBigDecimal()
                it[TripsTable.endLocation] = endAddress ?: "Localização não disponível"
                it[TripsTable.endTime] = now
                it[TripsTable.status] = TripStatus.CONCLUIDA
            }

            farthestPointCache.remove(tripId)
            lastPositionCache.remove(tripId)

            println("✅ Viagem diária #$tripId FINALIZADA")
            println("   📏 Distância percorrida: ${totalDistanceKm.format(2)} km")
            println("   📍 Ponto mais distante: ${farthestPoint.distanceFromStart.format(2)} km do início")
            println("   ⏱️  Duração: ${durationMinutes.toInt()} min")
            println("   🚀 Vel. máx: ${maxSpeed.format(1)} km/h | Vel. média: ${avgSpeed.format(1)} km/h")
            println("   🎯 Destino: ${endAddress ?: "Não disponível"}")
            println("   🕐 Ponto mais distante registrado em: ${farthestPoint.dateTime}")
        }
    }

    private suspend fun getAddressFromCoordinates(latitude: Double, longitude: Double): String? {
        return try {
            val response: HttpResponse = httpClient.get(GEOCODING_API_URL) {
                parameter("lat", latitude)
                parameter("lon", longitude)
                parameter("format", "json")
                parameter("addressdetails", 1)
                header("User-Agent", "FrotaGestor/1.0")
            }

            val jsonResponse = Json.parseToJsonElement(response.bodyAsText()).jsonObject
            val address = jsonResponse["address"]?.jsonObject

            val road = address?.get("road")?.jsonPrimitive?.content
            val suburb = address?.get("suburb")?.jsonPrimitive?.content
            val city = address?.get("city")?.jsonPrimitive?.content
                ?: address?.get("town")?.jsonPrimitive?.content
                ?: address?.get("village")?.jsonPrimitive?.content
            val state = address?.get("state")?.jsonPrimitive?.content

            buildString {
                road?.let { append(it) }
                if (suburb != null && suburb != road) {
                    if (isNotEmpty()) append(", ")
                    append(suburb)
                }
                city?.let {
                    if (isNotEmpty()) append(", ")
                    append(it)
                }
                state?.let {
                    if (isNotEmpty()) append(" - ")
                    append(it)
                }
            }.takeIf { it.isNotEmpty() }

        } catch (e: Exception) {
            println("⚠️ Erro ao buscar endereço: ${e.message}")
            null
        }
    }

    private fun calculateDistance(lat1: Double, lon1: Double, lat2: Double, lon2: Double): Double {
        val earthRadiusKm = 6371.0
        val dLat = Math.toRadians(lat2 - lat1)
        val dLon = Math.toRadians(lon2 - lon1)
        val a = sin(dLat / 2) * sin(dLat / 2) +
                cos(Math.toRadians(lat1)) * cos(Math.toRadians(lat2)) *
                sin(dLon / 2) * sin(dLon / 2)
        val c = 2 * atan2(sqrt(a), sqrt(1 - a))
        return earthRadiusKm * c
    }

    private fun calculateDuration(start: LocalDateTime, end: LocalDateTime): Double {
        val startInstant = start.toInstant(TimeZone.currentSystemDefault())
        val endInstant = end.toInstant(TimeZone.currentSystemDefault())
        val durationMs = (endInstant - startInstant).inWholeMilliseconds
        return durationMs / 60000.0
    }

    private fun Double.format(decimals: Int) = "%.${decimals}f".format(this)
}