package com.frotagestor.services

import com.frotagestor.database.DatabaseFactory
import com.frotagestor.database.models.*
import com.frotagestor.interfaces.TripStatus
import kotlinx.datetime.*
import org.jetbrains.exposed.sql.*
import org.jetbrains.exposed.sql.SqlExpressionBuilder.eq
import kotlin.math.*
import io.ktor.client.*
import io.ktor.client.request.*
import io.ktor.client.statement.*
import kotlinx.serialization.json.*
import kotlinx.coroutines.*
import java.util.concurrent.ConcurrentHashMap

class DailyTripService(
    private val httpClient: HttpClient = HttpClient()
) {

    companion object {
        private const val MIN_VALID_TRIP_DISTANCE_KM = 1.0
        private const val GEOCODING_API_URL = "https://nominatim.openstreetmap.org/reverse"
        private const val END_OF_DAY_HOUR = 23
        private const val END_OF_DAY_MINUTE = 0
    }

    // Último ponto conhecido por vehicleId — usado apenas quando odômetro é nulo (GT06)
    // Perda de dados limitada a um intervalo de envio em caso de restart do servidor
    private val lastKnownPosition = ConcurrentHashMap<Int, Pair<Double, Double>>()

    /* =========================
       AGENDAMENTO DIÁRIO
       ========================= */

    fun startDailyCleanup(scope: CoroutineScope) {
        scope.launch {
            while (true) {
                val now = Clock.System.now().toLocalDateTime(TimeZone.currentSystemDefault())
                val nextCleanup = calculateNextCleanupTime(now)
                val delayMs = (
                        nextCleanup.toInstant(TimeZone.currentSystemDefault()) -
                                now.toInstant(TimeZone.currentSystemDefault())
                        ).inWholeMilliseconds

                println("🕐 Próxima finalização de viagens diárias: $nextCleanup")
                delay(delayMs)
                finalizeAllDailyTrips()
            }
        }
    }

    private fun calculateNextCleanupTime(now: LocalDateTime): LocalDateTime {
        val today23h = LocalDateTime(
            now.date,
            LocalTime(END_OF_DAY_HOUR, END_OF_DAY_MINUTE)
        )

        return if (now >= today23h) {
            today23h.date.plus(1, DateTimeUnit.DAY)
                .atTime(END_OF_DAY_HOUR, END_OF_DAY_MINUTE)
        } else today23h
    }

    /* =========================
       PROCESSAMENTO GPS
       ========================= */

    suspend fun processGpsData(
        imei: String,
        vehicleId: Int,
        latitude: Double,
        longitude: Double,
        dateTime: LocalDateTime,
        speed: Double,
        ignition: Boolean,
        odometer: Long?
    ) {
        if (!ignition) {
            lastKnownPosition.remove(vehicleId)
            return
        }

        val today = dateTime.date

        val tripId = DatabaseFactory.dbQuery {
            val existingTrip = TripsTable
                .selectAll()
                .where {
                    (TripsTable.vehicleId eq vehicleId) and
                            (TripsTable.autoGenerated eq true) and
                            (TripsTable.status eq TripStatus.EM_ANDAMENTO)
                }
                .orderBy(TripsTable.startTime, SortOrder.DESC)
                .limit(1)
                .singleOrNull()

            if (existingTrip != null) {
                val tripDate = existingTrip[TripsTable.startTime].date
                if (tripDate == today) {
                    return@dbQuery existingTrip[TripsTable.id]
                } else {
                    finalizeTrip(existingTrip[TripsTable.id])
                }
            }

            createDailyTrip(imei, vehicleId, latitude, longitude, dateTime, odometer)
        }

        updateDailyTrip(tripId, vehicleId, latitude, longitude, dateTime, speed, odometer)
    }

    /* =========================
       CRIAÇÃO DA VIAGEM
       ========================= */

    private suspend fun createDailyTrip(
        imei: String,
        vehicleId: Int,
        latitude: Double,
        longitude: Double,
        dateTime: LocalDateTime,
        odometer: Long?
    ): Int {

        val gpsDeviceId = GpsDevicesTable
            .selectAll()
            .where { GpsDevicesTable.imei eq imei }
            .singleOrNull()
            ?.get(GpsDevicesTable.id)

        val defaultDriverId = VehiclesTable
            .selectAll()
            .where { VehiclesTable.id eq vehicleId }
            .singleOrNull()
            ?.get(VehiclesTable.defaultDriverId)

        val startAddress = getAddressFromCoordinates(latitude, longitude)

        val tripId = TripsTable.insert {
            it[TripsTable.vehicleId]    = vehicleId
            it[driverId]                = defaultDriverId
            it[TripsTable.gpsDeviceId]  = gpsDeviceId
            it[startLatitude]           = latitude.toBigDecimal()
            it[startLongitude]          = longitude.toBigDecimal()
            it[startLocation]           = startAddress ?: "Localização não disponível"
            it[startTime]               = dateTime
            it[startOdometer]           = odometer
            it[distanceKm]              = 0.toBigDecimal()
            it[status]                  = TripStatus.EM_ANDAMENTO
            it[autoGenerated]           = true
            it[maxSpeedKmh]             = 0.toBigDecimal()
            it[endLatitude]             = latitude.toBigDecimal()
            it[endLongitude]            = longitude.toBigDecimal()
        }[TripsTable.id]

        println("🚗 Viagem diária criada #$tripId (veículo $vehicleId)")
        return tripId
    }

    /* =========================
       ATUALIZAÇÃO DA VIAGEM
       ========================= */

    private suspend fun updateDailyTrip(
        tripId: Int,
        vehicleId: Int,
        latitude: Double,
        longitude: Double,
        dateTime: LocalDateTime,
        speed: Double,
        odometer: Long?
    ) {
        DatabaseFactory.dbQuery {

            val trip = TripsTable
                .selectAll()
                .where { TripsTable.id eq tripId }
                .singleOrNull() ?: return@dbQuery

            val startLat = trip[TripsTable.startLatitude]!!.toDouble()
            val startLon = trip[TripsTable.startLongitude]!!.toDouble()

            val totalDistanceKm = if (odometer != null) {
                // Suntech: distância pelo odômetro real do dispositivo
                val startOdometer = trip[TripsTable.startOdometer] ?: 0L
                ((odometer - startOdometer) / 1000.0).coerceAtLeast(0.0)
            } else {
                // GT06: haversine acumulado ponto a ponto via lastKnownPosition
                val accumulated = trip[TripsTable.distanceKm]?.toDouble() ?: 0.0
                val lastPos = lastKnownPosition[vehicleId]
                if (lastPos != null) {
                    accumulated + calculateDistance(lastPos.first, lastPos.second, latitude, longitude)
                } else {
                    accumulated
                }
            }

            lastKnownPosition[vehicleId] = Pair(latitude, longitude)

            val currentEndLat = trip[TripsTable.endLatitude]!!.toDouble()
            val currentEndLon = trip[TripsTable.endLongitude]!!.toDouble()

            val distanceCurrent = calculateDistance(startLat, startLon, latitude, longitude)
            val distanceStored  = calculateDistance(startLat, startLon, currentEndLat, currentEndLon)
            val isFarther       = distanceCurrent > distanceStored

            val newMaxSpeed = maxOf(
                trip[TripsTable.maxSpeedKmh]?.toDouble() ?: 0.0,
                speed
            )

            TripsTable.update({ TripsTable.id eq tripId }) {
                it[endTime]    = dateTime
                it[distanceKm] = totalDistanceKm.toBigDecimal()
                it[maxSpeedKmh] = newMaxSpeed.toBigDecimal()

                if (isFarther) {
                    it[endLatitude]  = latitude.toBigDecimal()
                    it[endLongitude] = longitude.toBigDecimal()
                }
            }

            if (isFarther) {
                println("📍 Novo ponto mais distante (${distanceCurrent.format(2)} km)")
            }
        }
    }

    /* =========================
       FINALIZAÇÃO
       ========================= */

    private suspend fun finalizeAllDailyTrips() {
        println("🌙 Finalizando viagens diárias...")

        DatabaseFactory.dbQuery {
            TripsTable
                .selectAll()
                .where {
                    (TripsTable.status eq TripStatus.EM_ANDAMENTO) and
                            (TripsTable.autoGenerated eq true)
                }
                .forEach { finalizeTrip(it[TripsTable.id]) }
        }
    }

    private suspend fun finalizeTrip(tripId: Int) {
        DatabaseFactory.dbQuery {

            val trip = TripsTable
                .selectAll()
                .where { TripsTable.id eq tripId }
                .singleOrNull() ?: return@dbQuery

            val totalDistanceKm = trip[TripsTable.distanceKm]?.toDouble() ?: 0.0

            if (totalDistanceKm < MIN_VALID_TRIP_DISTANCE_KM) {
                TripsTable.deleteWhere { TripsTable.id eq tripId }
                println("🗑️ Viagem #$tripId deletada (sem movimento)")
                return@dbQuery
            }

            val endLat = trip[TripsTable.endLatitude]!!.toDouble()
            val endLon = trip[TripsTable.endLongitude]!!.toDouble()

            val endAddress = getAddressFromCoordinates(endLat, endLon)

            TripsTable.update({ TripsTable.id eq tripId }) {
                it[endLocation] = endAddress ?: "Localização não disponível"
                it[status]      = TripStatus.CONCLUIDA
            }

            println("✅ Viagem #$tripId finalizada")
        }
    }

    /* =========================
       UTILITÁRIOS
       ========================= */

    private suspend fun getAddressFromCoordinates(
        latitude: Double,
        longitude: Double
    ): String? = try {
        val response = httpClient.get(GEOCODING_API_URL) {
            parameter("lat", latitude)
            parameter("lon", longitude)
            parameter("format", "json")
            header("User-Agent", "FrotaGestor/1.0")
        }

        val json = Json.parseToJsonElement(response.bodyAsText()).jsonObject
        json["display_name"]?.jsonPrimitive?.content

    } catch (e: Exception) {
        println("⚠️ Erro geocoding: ${e.message}")
        null
    }

    private fun calculateDistance(
        lat1: Double,
        lon1: Double,
        lat2: Double,
        lon2: Double
    ): Double {
        val r = 6371.0
        val dLat = Math.toRadians(lat2 - lat1)
        val dLon = Math.toRadians(lon2 - lon1)
        val a =
            sin(dLat / 2).pow(2) +
                    cos(Math.toRadians(lat1)) *
                    cos(Math.toRadians(lat2)) *
                    sin(dLon / 2).pow(2)
        return 2 * r * atan2(sqrt(a), sqrt(1 - a))
    }

    private fun Double.format(decimals: Int) = "%.${decimals}f".format(this)
}