export interface Trip {
  id?: number;
  vehicleId: number;
  driverId?: number | null;  // 🔄 ALTERADO: agora nullable
  startLocation?: string | null;
  endLocation?: string | null;
  
  // 🆕 Coordenadas geográficas de início
  startLatitude?: number | null;
  startLongitude?: number | null;
  
  // 🆕 Coordenadas geográficas de fim
  endLatitude?: number | null;
  endLongitude?: number | null;
  
  startTime: Date | string;
  endTime?: Date | string | null;
  distanceKm?: number | null;
  
  // 🆕 Campos de automação GPS
  autoGenerated: boolean;
  gpsDeviceId?: number | null;
  
  // 🆕 Métricas de velocidade
  maxSpeedKmh?: number | null;
  avgSpeedKmh?: number | null;
  
  status: TripStatus;
  
  // Campos de join (não persistidos)
  driverName?: string | null;
  vehiclePlate?: string | null;
}

export enum TripStatus {
  PLANEJADA = 'PLANEJADA',
  EM_ANDAMENTO = 'EM_ANDAMENTO',
  CONCLUIDA = 'CONCLUIDA',
  CANCELADA = 'CANCELADA',
}

export interface TripIndicators {
  totalTrips: number;
  inProgress: number;
  completed: number;
  canceled: number;
  totalDistance: number;
  avgDistance: number;
  lastTrip: {
    date: string;
    driverName: string;
    vehiclePlate: string;
  };
}

export interface TripReport {
  distributions: {
    byStatus: { status: TripStatus; count: number }[];
    byVehicle: { vehiclePlate: string; count: number; totalCost: number }[];
    byDriver: { driverName: string; count: number; totalCost: number }[];
    byDestination: {
      destination: string;
      totalTrips: number;
      totalCost: number;
    }[];
  };
}
