package com.frotagestor.database.models

import com.frotagestor.interfaces.TripStatus
import org.jetbrains.exposed.sql.Table
import org.jetbrains.exposed.sql.kotlin.datetime.datetime

object TripsTable : Table("trips") {
    val id = integer("id").autoIncrement()
    val vehicleId = integer("vehicle_id").references(VehiclesTable.id)
    val driverId = integer("driver_id").references(DriversTable.id).nullable()
    val startLocation = varchar("start_location", 255).nullable()
    val endLocation = varchar("end_location", 255).nullable()
    val startTime = datetime("start_time")
    val endTime = datetime("end_time").nullable()
    val distanceKm = decimal("distance_km", 10, 2).nullable()
    val status = enumerationByName("status", 20, TripStatus::class)
    val startLatitude = decimal("start_latitude", 10, 8).nullable()
    val startLongitude = decimal("start_longitude", 11, 8).nullable()
    val endLatitude = decimal("end_latitude", 10, 8).nullable()
    val endLongitude = decimal("end_longitude", 11, 8).nullable()
    val autoGenerated = bool("auto_generated").default(false)
    val gpsDeviceId = integer("gps_device_id").references(GpsDevicesTable.id).nullable()
    val maxSpeedKmh = decimal("max_speed_kmh", 5, 2).nullable()
    val avgSpeedKmh = decimal("avg_speed_kmh", 5, 2).nullable()
    val startOdometer = long("start_odometer").nullable()

    override val primaryKey = PrimaryKey(id)
}